# Generated by Django 3.1 on 2020-11-12 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='NA', max_length=100)),
                ('contactNo', models.IntegerField(default=0, max_length=10)),
                ('address', models.CharField(default='NA', max_length=100)),
                ('batch', models.CharField(default='NA', max_length=10)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
