# Generated by Django 3.1 on 2020-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRReaderAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('answer', models.CharField(default='NA', max_length=120)),
                ('answerType', models.CharField(default='NA', max_length=30)),
                ('negative', models.BooleanField(default=True)),
                ('description', models.CharField(default='NA', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='student_info',
            name='rollno',
            field=models.CharField(default='20XXIMX-XXX', max_length=10),
        ),
    ]
