# Generated by Django 3.1 on 2020-11-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMRReaderAPI', '0003_auto_20201112_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('answer', models.CharField(default='NA', max_length=120)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='OMRReaderAPI.quiz_info')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='OMRReaderAPI.student_info')),
            ],
        ),
    ]
