# Generated by Django 3.1 on 2020-11-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRReaderAPI', '0006_auto_20201115_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='rollno',
            field=models.CharField(default='20XXIMX-XXX', max_length=20),
        ),
    ]
