# Generated by Django 3.1 on 2020-11-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRReaderAPI', '0007_auto_20201115_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='contactNo',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
